apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubernetes.yaml
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: newapi-risk-platform
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/lifecycle
