const state={token:sessionStorage.getItem('riskgate_token')||'',user:null,page:'overview',routes:[],profiles:[],rules:[]};
const $=selector=>document.querySelector(selector);const $$=selector=>[...document.querySelectorAll(selector)];
const titles={overview:['运行概览','服务状态、阻断量与存储积压'],routes:['渠道路由','New API 到模型渠道的安全转发配置'],profiles:['审计模型','低延迟小模型、阈值与失败策略'],rules:['Cyber 规则','确定性规则优先于模型分类'],traces:['请求追踪','默认七天窗口，原始 Prompt 不落库'],storage:['存储策略','PostgreSQL、Redis 补偿与 Kafka 长期事件流'],dryrun:['审计试跑','不转发上游，仅查看规则与模型判定']};
function esc(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));}
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className='toast'+(error?' error':'');el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,4500);}
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(state.token)headers.Authorization='Bearer '+state.token;const response=await fetch('/admin/api/v1/'+path,{...options,headers});if(response.status===401&&path!=='login'){logout();throw new Error('登录已失效');}if(response.status===204)return null;let body={};try{body=await response.json();}catch{}if(!response.ok)throw new Error(body?.error?.code||('HTTP '+response.status));return body;}
function setSession(token,user){state.token=token;state.user=user;sessionStorage.setItem('riskgate_token',token);sessionStorage.setItem('riskgate_user',JSON.stringify(user));showApp();}
function logout(){state.token='';state.user=null;sessionStorage.removeItem('riskgate_token');sessionStorage.removeItem('riskgate_user');$('#appView').hidden=true;$('#loginView').hidden=false;}
function showApp(){if(!state.user){try{state.user=JSON.parse(sessionStorage.getItem('riskgate_user')||'null');}catch{state.user=null;}}$('#loginView').hidden=true;$('#appView').hidden=false;$('#currentUser').textContent=state.user?`${state.user.username} · ${state.user.role}`:'';showPage(state.page);}
async function showPage(page){state.page=page;$$('nav button').forEach(button=>button.classList.toggle('active',button.dataset.page===page));$$('.page').forEach(section=>section.classList.toggle('active',section.id==='page-'+page));$('#pageTitle').textContent=titles[page][0];$('#pageSubtitle').textContent=titles[page][1];try{await loaders[page]();}catch(error){toast(error.message,true);}}
const loaders={overview:loadOverview,routes:loadRoutes,profiles:loadProfiles,rules:loadRules,traces:loadTraces,storage:loadStorage,dryrun:async()=>{await fetchProfiles();renderProfileOptions();}};
function parseJSONField(value,label){if(!value.trim())return undefined;try{return JSON.parse(value);}catch{throw new Error(label+'不是合法 JSON');}}
function prettyJSON(value){if(!value)return'';try{return JSON.stringify(value,null,2);}catch{return'';}}

$('#loginForm').addEventListener('submit',async event=>{event.preventDefault();const form=new FormData(event.currentTarget);try{const data=await api('login',{method:'POST',body:JSON.stringify({username:form.get('username'),password:form.get('password')})});setSession(data.token,data.user);}catch(error){toast(error.message,true);}});
$('#logoutBtn').addEventListener('click',logout);$('#refreshBtn').addEventListener('click',()=>showPage(state.page));$$('nav button').forEach(button=>button.addEventListener('click',()=>showPage(button.dataset.page)));$$('[data-close]').forEach(button=>button.addEventListener('click',()=>document.getElementById(button.dataset.close).close()));

async function loadOverview(){const data=await api('runtime');const stats=data.stats||{};const cards=[['启用路由',stats.routes_enabled||0,'routes'],['近一小时请求',stats.traces_last_hour||0,'requests'],['近一小时 555',stats.blocked_last_hour||0,'blocked'],['待投递 Outbox',stats.outbox_pending||0,'pending']];$('#metricCards').innerHTML=cards.map(card=>`<div class="card"><span>${esc(card[0])}</span><strong>${esc(card[1])}</strong><small>${esc(card[2])}</small></div>`).join('');const components=data.components||{};const componentRows=[['PostgreSQL',components.postgres],['Redis',components.redis_enabled?components.redis_healthy:null],['Kafka',components.kafka_enabled]];$('#componentStatus').innerHTML=componentRows.map(([name,value])=>`<div class="status-item"><span><i class="dot ${value===false?'off':''}"></i>${esc(name)}</span><b>${value===null?'disabled':value?'healthy':'unavailable'}</b></div>`).join('');const policy=data.storage_policy||{};$('#overviewStorage').innerHTML=`<p><b>${esc(policy.retention_days||7)} 天</b> PostgreSQL 热窗口 · Redis 补偿 ${policy.redis_buffer_enabled?'已启用':'已关闭'} · Kafka ${policy.kafka_enabled?'已启用':'已关闭'}</p><p class="muted">Default partition rows: ${esc(stats.default_partition_rows||0)} · Dead outbox: ${esc(stats.outbox_dead||0)}</p>`;}

async function fetchProfiles(){const data=await api('audit-profiles');state.profiles=data.items||[];return state.profiles;}
function renderProfileOptions(){const options='<option value="">仅规则引擎</option>'+state.profiles.map(profile=>`<option value="${esc(profile.id)}">${esc(profile.name)} · ${esc(profile.model)}</option>`).join('');const routeSelect=$('#routeForm [name=audit_profile_id]');const routeValue=routeSelect.value;routeSelect.innerHTML=options;routeSelect.value=routeValue;const drySelect=$('#dryProfile');const dryValue=drySelect.value;drySelect.innerHTML=options;drySelect.value=dryValue;}
function profileName(id){return state.profiles.find(profile=>profile.id===id)?.name;}

async function loadRoutes(){if(state.profiles.length===0)await fetchProfiles();renderProfileOptions();const data=await api('routes');state.routes=data.items||[];$('#routesBody').innerHTML=state.routes.map(route=>`<tr><td><b>${esc(route.name)}</b><div class="muted mono">${esc(route.newapi_base_url)}</div></td><td><span class="badge">${esc(route.slug)}</span> <span class="muted">${esc(route.upstream_kind)}</span></td><td class="mono">${esc(route.upstream_base_url)}</td><td>${esc(route.rate_limit_rps)} rps / ${esc(route.rate_limit_burst)}<div class="muted">并发 ${esc(route.max_inflight)}</div></td><td>${esc(profileName(route.audit_profile_id)||'仅规则')}</td><td><span class="badge ${route.enabled?'good':'bad'}">${route.enabled?'enabled':'disabled'}</span></td><td><div class="row-actions"><button data-copy="${esc(route.newapi_base_url)}" class="secondary">复制 URL</button><button data-edit-route="${esc(route.id)}" class="secondary">编辑</button><button data-delete-route="${esc(route.id)}" class="delete">删除</button></div></td></tr>`).join('')||'<tr><td colspan="7" class="muted">尚未配置路由</td></tr>';}
$('#routesBody').addEventListener('click',async event=>{const copy=event.target.dataset.copy;if(copy){try{await navigator.clipboard.writeText(copy);toast('Base URL 已复制');}catch{window.prompt('复制 Base URL：',copy);}return;}const edit=event.target.dataset.editRoute;if(edit){openRoute(state.routes.find(route=>route.id===edit));return;}const remove=event.target.dataset.deleteRoute;if(remove&&confirm('确定删除此路由？')){try{await api('routes/'+remove,{method:'DELETE'});toast('路由已删除');await loadRoutes();}catch(error){toast(error.message,true);}}});
$('#newRouteBtn').addEventListener('click',()=>openRoute(null));
function openRoute(route){const form=$('#routeForm');form.reset();form.elements.id.value=route?.id||'';form.elements.name.value=route?.name||'';form.elements.slug.value=route?.slug||'';form.elements.upstream_kind.value=route?.upstream_kind||'openai';form.elements.upstream_base_url.value=route?.upstream_base_url||'';form.elements.audit_profile_id.value=route?.audit_profile_id||'';form.elements.rate_limit_rps.value=route?.rate_limit_rps||100;form.elements.rate_limit_burst.value=route?.rate_limit_burst||200;form.elements.max_inflight.value=route?.max_inflight||1000;form.elements.request_timeout_ms.value=route?.request_timeout_ms||300000;form.elements.extra_headers.value='';form.elements.extra_headers.placeholder=route?.has_extra_headers?'已配置加密请求头；留空保持不变，输入 {} 清空':'{"X-Provider-Tenant":"tenant-a"}';form.elements.upstream_error_policy.value=prettyJSON(route?.upstream_error_policy);form.elements.enabled.checked=route?route.enabled:true;form.elements.allow_private_upstream.checked=!!route?.allow_private_upstream;$('#routeDialog').showModal();}
$('#routeForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;try{const body={name:form.elements.name.value,slug:form.elements.slug.value,upstream_kind:form.elements.upstream_kind.value,upstream_base_url:form.elements.upstream_base_url.value,upstream_api_key:form.elements.upstream_api_key.value,client_token:form.elements.client_token.value,audit_profile_id:form.elements.audit_profile_id.value||null,rate_limit_rps:Number(form.elements.rate_limit_rps.value),rate_limit_burst:Number(form.elements.rate_limit_burst.value),max_inflight:Number(form.elements.max_inflight.value),request_timeout_ms:Number(form.elements.request_timeout_ms.value),enabled:form.elements.enabled.checked,allow_private_upstream:form.elements.allow_private_upstream.checked};const headers=parseJSONField(form.elements.extra_headers.value,'附加请求头');const policy=parseJSONField(form.elements.upstream_error_policy.value,'上游错误策略');if(headers!==undefined)body.extra_headers=headers;if(policy!==undefined)body.upstream_error_policy=policy;const id=form.elements.id.value;const saved=await api(id?'routes/'+id:'routes',{method:id?'PUT':'POST',body:JSON.stringify(body)});$('#routeDialog').close();toast('路由已保存');if(saved.client_token)window.prompt('网关令牌只显示一次，请复制到 New API 渠道 Key：',saved.client_token);await loadRoutes();}catch(error){toast(error.message,true);}});

async function loadProfiles(){await fetchProfiles();renderProfileOptions();$('#profilesBody').innerHTML=state.profiles.map(profile=>`<tr><td><b>${esc(profile.name)}</b></td><td>${esc(profile.model)}</td><td class="mono">${esc(profile.endpoint)}</td><td>${esc(profile.block_threshold)}</td><td><span class="badge ${profile.fail_mode==='closed'?'good':profile.fail_mode==='open'?'bad':'warn'}">${esc(profile.fail_mode)}</span></td><td>${profile.enabled?'enabled':'disabled'}</td><td><div class="row-actions"><button data-edit-profile="${esc(profile.id)}" class="secondary">编辑</button><button data-delete-profile="${esc(profile.id)}" class="delete">删除</button></div></td></tr>`).join('')||'<tr><td colspan="7" class="muted">尚未配置审计模型</td></tr>';}
$('#profilesBody').addEventListener('click',async event=>{const edit=event.target.dataset.editProfile;if(edit){openProfile(state.profiles.find(profile=>profile.id===edit));return;}const remove=event.target.dataset.deleteProfile;if(remove&&confirm('删除后引用它的路由将退回仅规则审计，是否继续？')){try{await api('audit-profiles/'+remove,{method:'DELETE'});toast('审计模型已删除');await loadProfiles();}catch(error){toast(error.message,true);}}});
$('#newProfileBtn').addEventListener('click',()=>openProfile(null));
function openProfile(profile){const form=$('#profileForm');form.reset();form.elements.id.value=profile?.id||'';form.elements.name.value=profile?.name||'';form.elements.endpoint.value=profile?.endpoint||'';form.elements.model.value=profile?.model||'';form.elements.fail_mode.value=profile?.fail_mode||'closed';form.elements.block_threshold.value=profile?.block_threshold??.72;form.elements.timeout_ms.value=profile?.timeout_ms||8000;form.elements.max_input_chars.value=profile?.max_input_chars||32000;form.elements.cache_ttl_seconds.value=profile?.cache_ttl_seconds??600;form.elements.system_prompt.value=profile?.system_prompt||'';form.elements.enabled.checked=profile?profile.enabled:true;$('#profileDialog').showModal();}
$('#profileForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;const body={name:form.elements.name.value,endpoint:form.elements.endpoint.value,model:form.elements.model.value,api_key:form.elements.api_key.value,fail_mode:form.elements.fail_mode.value,block_threshold:Number(form.elements.block_threshold.value),timeout_ms:Number(form.elements.timeout_ms.value),max_input_chars:Number(form.elements.max_input_chars.value),cache_ttl_seconds:Number(form.elements.cache_ttl_seconds.value),system_prompt:form.elements.system_prompt.value,enabled:form.elements.enabled.checked};const id=form.elements.id.value;try{await api(id?'audit-profiles/'+id:'audit-profiles',{method:id?'PUT':'POST',body:JSON.stringify(body)});$('#profileDialog').close();toast('审计模型已保存');await loadProfiles();}catch(error){toast(error.message,true);}});

async function loadRules(){const data=await api('rules');state.rules=data.items||[];$('#rulesBody').innerHTML=state.rules.map(rule=>`<tr><td><b>${esc(rule.name)}</b></td><td>${esc(rule.category)}</td><td><span class="badge ${rule.action==='block'?'bad':rule.action==='review'?'warn':'good'}">${esc(rule.action)}</span> ${esc(rule.score)}</td><td>${esc(rule.priority)}</td><td>${rule.builtin?'内置':'自定义'}</td><td>${rule.enabled?'enabled':'disabled'}</td><td><div class="row-actions"><button data-edit-rule="${esc(rule.id)}" class="secondary">编辑</button>${rule.builtin?'':`<button data-delete-rule="${esc(rule.id)}" class="delete">删除</button>`}</div></td></tr>`).join('')||'<tr><td colspan="7" class="muted">尚无规则</td></tr>';}
$('#rulesBody').addEventListener('click',async event=>{const edit=event.target.dataset.editRule;if(edit){openRule(state.rules.find(rule=>rule.id===edit));return;}const remove=event.target.dataset.deleteRule;if(remove&&confirm('确定删除此规则？')){try{await api('rules/'+remove,{method:'DELETE'});toast('规则已删除');await loadRules();}catch(error){toast(error.message,true);}}});
$('#newRuleBtn').addEventListener('click',()=>openRule(null));
function openRule(rule){const form=$('#ruleForm');form.reset();form.elements.id.value=rule?.id||'';form.elements.name.value=rule?.name||'';form.elements.category.value=rule?.category||'';form.elements.pattern.value=rule?.pattern||'';form.elements.action.value=rule?.action||'block';form.elements.score.value=rule?.score??1;form.elements.priority.value=rule?.priority||100;form.elements.enabled.checked=rule?rule.enabled:true;$('#ruleDialog').showModal();}
$('#ruleForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;const body={name:form.elements.name.value,category:form.elements.category.value,pattern:form.elements.pattern.value,action:form.elements.action.value,score:Number(form.elements.score.value),priority:Number(form.elements.priority.value),enabled:form.elements.enabled.checked};const id=form.elements.id.value;try{await api(id?'rules/'+id:'rules',{method:id?'PUT':'POST',body:JSON.stringify(body)});$('#ruleDialog').close();toast('规则已保存');await loadRules();}catch(error){toast(error.message,true);}});

async function loadTraces(){const form=new FormData($('#traceFilter'));const query=new URLSearchParams();for(const[key,value]of form.entries())if(value)query.set(key,value);query.set('limit','200');const data=await api('traces?'+query.toString());$('#tracesBody').innerHTML=(data.items||[]).map(trace=>`<tr><td>${esc(new Date(trace.created_at).toLocaleString())}<div class="mono muted">${esc(trace.external_request_id||trace.id)}</div></td><td><b>${esc(trace.route_slug||'-')}</b><div class="muted">${esc(trace.model||'-')}</div></td><td><span class="badge ${trace.normalized_code===555?'bad':trace.outcome==='allowed'?'good':'warn'}">${esc(trace.outcome||'-')}</span></td><td>${esc(trace.http_status)}${trace.normalized_code?` / ${esc(trace.normalized_code)}`:''}</td><td>${esc(trace.risk_category||'-')}<div class="muted">${esc(trace.risk_score||0)} · ${esc(trace.risk_reason_code||'')}</div></td><td>${esc(trace.total_latency_ms)} ms<div class="muted">audit ${esc(trace.audit_latency_ms)} / upstream ${esc(trace.upstream_latency_ms)}</div></td></tr>`).join('')||'<tr><td colspan="6" class="muted">没有匹配的请求</td></tr>';}
$('#traceFilter').addEventListener('submit',event=>{event.preventDefault();loadTraces().catch(error=>toast(error.message,true));});

async function loadStorage(){const policy=await api('storage-policy');const form=$('#storageForm');for(const name of['retention_days','redis_buffer_ttl_hours','kafka_retention_hours'])form.elements[name].value=policy[name];for(const name of['postgres_enabled','redis_buffer_enabled','kafka_enabled'])form.elements[name].checked=!!policy[name];}
$('#storageForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;const body={retention_days:Number(form.elements.retention_days.value),postgres_enabled:form.elements.postgres_enabled.checked,redis_buffer_enabled:form.elements.redis_buffer_enabled.checked,redis_buffer_ttl_hours:Number(form.elements.redis_buffer_ttl_hours.value),kafka_enabled:form.elements.kafka_enabled.checked,kafka_retention_hours:Number(form.elements.kafka_retention_hours.value),store_raw_prompt:false};try{await api('storage-policy',{method:'PUT',body:JSON.stringify(body)});toast('存储策略已保存');}catch(error){toast(error.message,true);}});

$('#dryRunForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;$('#dryRunResult').textContent='执行中…';try{const data=await api('audit/dry-run',{method:'POST',body:JSON.stringify({profile_id:form.elements.profile_id.value||null,text:form.elements.text.value})});$('#dryRunResult').textContent=JSON.stringify(data,null,2);}catch(error){$('#dryRunResult').textContent=error.message;toast(error.message,true);}});

if(state.token)showApp();else logout();
