const state={token:sessionStorage.getItem('riskgate_token')||'',user:null,page:'overview',routes:[],profiles:[],rules:[]};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const titles={overview:['运行概览','服务状态、阻断量与存储积压'],routes:['渠道路由','New API 到模型渠道的安全转发配置'],profiles:['审计模型','低延迟小模型与失败策略'],rules:['Cyber 规则','确定性规则优先于模型分类'],traces:['请求追踪','默认七天窗口，原始 Prompt 不落库'],storage:['存储策略','PostgreSQL、Redis 补偿与 Kafka 长期事件流'],dryrun:['审计试跑','不转发上游，仅查看规则与模型判定']};
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className='toast'+(error?' error':'');el.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>el.hidden=true,4500);}
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(state.token)headers.Authorization='Bearer '+state.token;const res=await fetch('/admin/api/v1/'+path,{...options,headers});if(res.status===401&&path!=='login'){logout();throw new Error('登录已失效');}if(res.status===204)return null;let body={};try{body=await res.json();}catch{}if(!res.ok)throw new Error(body?.error?.code||('HTTP '+res.status));return body;}
function setSession(token,user){state.token=token;state.user=user;sessionStorage.setItem('riskgate_token',token);sessionStorage.setItem('riskgate_user',JSON.stringify(user));showApp();}
function logout(){state.token='';state.user=null;sessionStorage.removeItem('riskgate_token');sessionStorage.removeItem('riskgate_user');$('#appView').hidden=true;$('#loginView').hidden=false;}
function showApp(){if(!state.user){try{state.user=JSON.parse(sessionStorage.getItem('riskgate_user')||'null');}catch{}}$('#loginView').hidden=true;$('#appView').hidden=false;$('#currentUser').textContent=state.user?`${state.user.username} · ${state.user.role}`:'';showPage(state.page);}
async function showPage(page){state.page=page;$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$$('.page').forEach(p=>p.classList.toggle('active',p.id==='page-'+page));$('#pageTitle').textContent=titles[page][0];$('#pageSubtitle').textContent=titles[page][1];try{await loaders[page]();}catch(e){toast(e.message,true);}}
const loaders={overview:loadOverview,routes:loadRoutes,profiles:loadProfiles,rules:loadRules,traces:loadTraces,storage:loadStorage,dryrun:loadProfiles};

$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const data=await api('login',{method:'POST',body:JSON.stringify({username:f.get('username'),password:f.get('password')})});setSession(data.token,data.user);}catch(err){toast(err.message,true);}});
$('#logoutBtn').addEventListener('click',logout);$('#refreshBtn').addEventListener('click',()=>showPage(state.page));$$('nav button').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));

async function loadOverview(){const d=await api('runtime');const st=d.stats||{};const cards=[['启用路由',st.routes_enabled||0,'routes'],['近一小时请求',st.traces_last_hour||0,'requests'],['近一小时 555',st.blocked_last_hour||0,'blocked'],['待投递 Outbox',st.outbox_pending||0,'pending']];$('#metricCards').innerHTML=cards.map(x=>`<div class="card"><span>${esc(x[0])}</span><strong>${esc(x[1])}</strong><small>${esc(x[2])}</small></div>`).join('');const c=d.components||{};$('#componentStatus').innerHTML=[['PostgreSQL',c.postgres],['Redis',c.redis_enabled?c.redis_healthy:null],['Kafka',c.kafka_enabled]].map(([n,v])=>`<div class="status-item"><span><i class="dot ${v===false?'off':''}"></i>${esc(n)}</span><b>${v===null?'disabled':v?'healthy':'unavailable'}</b></div>`).join('');const p=d.storage_policy||{};$('#overviewStorage').innerHTML=`<p><b>${esc(p.retention_days||7)} 天</b> PostgreSQL 热窗口 · Redis 补偿 ${p.redis_buffer_enabled?'已启用':'已关闭'} · Kafka ${p.kafka_enabled?'已启用':'已关闭'}</p><p class="muted">Default partition rows: ${esc(st.default_partition_rows||0)} · Dead outbox: ${esc(st.outbox_dead||0)}</p>`;}

async function loadRoutes(){const d=await api('routes');state.routes=d.items||[];renderRouteProfileOptions();$('#routesBody').innerHTML=state.routes.map(r=>`<tr><td><b>${esc(r.name)}</b><div class="muted mono">${esc(r.newapi_base_url)}</div></td><td><span class="badge">${esc(r.slug)}</span> <span class="muted">${esc(r.upstream_kind)}</span></td><td class="mono">${esc(r.upstream_base_url)}</td><td>${esc(r.rate_limit_rps)} rps / ${esc(r.rate_limit_burst)}<div class="muted">并发 ${esc(r.max_inflight)}</div></td><td>${esc(profileName(r.audit_profile_id)||'仅规则')}</td><td><span class="badge ${r.enabled?'good':'bad'}">${r.enabled?'enabled':'disabled'}</span></td><td><div class="row-actions"><button data-copy="${esc(r.newapi_base_url)}" class="secondary">复制 URL</button><button data-edit-route="${esc(r.id)}" class="secondary">编辑</button><button data-delete-route="${esc(r.id)}" class="delete">删除</button></div></td></tr>`).join('')||'<tr><td colspan="7" class="muted">尚未配置路由</td></tr>';}
function profileName(id){return state.profiles.find(x=>x.id===id)?.name;}
function renderRouteProfileOptions(){const select=$('#routeForm [name=audit_profile_id]');const current=select.value;select.innerHTML='<option value="">仅规则引擎</option>'+state.profiles.map(p=>`<option value="${esc(p.id)}">${esc(p.name)} · ${esc(p.model)}</option>`).join('');select.value=current;const dry=$('#dryProfile');if(dry){const v=dry.value;dry.innerHTML='<option value="">仅规则引擎</option>'+state.profiles.map(p=>`<option value="${esc(p.id)}">${esc(p.name)} · ${esc(p.model)}</option>`).join('');dry.value=v;}}
$('#routesBody').addEventListener('click',async e=>{const copy=e.target.dataset.copy;if(copy){await navigator.clipboard.writeText(copy);toast('Base URL 已复制');return;}const edit=e.target.dataset.editRoute;if(edit){openRoute(state.routes.find(x=>x.id===edit));return;}const del=e.target.dataset.deleteRoute;if(del&&confirm('确定删除此路由？')){try{await api('routes/'+del,{method:'DELETE'});toast('路由已删除');loadRoutes();}catch(err){toast(err.message,true);}}});
$('#newRouteBtn').addEventListener('click',()=>openRoute(null));function openRoute(r){const f=$('#routeForm');f.reset();f.elements.id.value=r?.id||'';f.elements.name.value=r?.name||'';f.elements.slug.value=r?.slug||'';f.elements.upstream_kind.value=r?.upstream_kind||'openai';f.elements.upstream_base_url.value=r?.upstream_base_url||'';f.elements.audit_profile_id.value=r?.audit_profile_id||'';f.elements.rate_limit_rps.value=r?.rate_limit_rps||100;f.elements.rate_limit_burst.value=r?.rate_limit_burst||200;f.elements.max_inflight.value=r?.max_inflight||1000;f.elements.request_timeout_ms.value=r?.request_timeout_ms||300000;f.elements.enabled.checked=r?r.enabled:true;f.elements.allow_private_upstream.checked=!!r?.allow_private_upstream;$('#routeDialog').showModal();}
$('#routeForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;const body={name:f.elements.name.value,slug:f.elements.slug.value,upstream_kind:f.elements.upstream_kind.value,upstream_base_url:f.elements.upstream_base_url.value,upstream_api_key:f.elements.upstream_api_key.value,client_token:f.elements.client_token.value,audit_profile_id:f.elements.audit_profile_id.value||null,rate_limit_rps:Number(f.elements.rate_limit_rps.value),rate_limit_burst:Number(f.elements.rate_limit_burst.value),max_inflight:Number(f.elements.max_inflight.value),request_timeout_ms:Number(f.elements.request_timeout_ms.value),enabled:f.elements.enabled.checked,allow_private_upstream:f.elements.allow_private_upstream.checked};const id=f.elements.id.value;try{const saved=await api(id?'routes/'+id:'routes',{method:id?'PUT':'POST',body:JSON.stringify(body)});$('#routeDialog').close();toast('路由已保存');if(saved.client_token)window.prompt('网关令牌只显示一次，请复制到 New API 渠道 Key：',saved.client_token);await loadRoutes();}catch(err){toast(err.message,true);}});

async function loadProfiles(){const d=await api('audit-profiles');state.profiles=d.items||[];renderRouteProfileOptions();$('#profilesBody').innerHTML=state.profiles.map(p=>`<tr><td><b>${esc(p.name)}</b></td><td>${esc(p.model)}</td><td class="mono">${esc(p.endpoint)}</td><td>${esc(p.block_threshold)}</td><td><span class="badge ${p.fail_mode==='closed'?'good':p.fail_mode==='open'?'bad':'warn'}">${esc(p.fail_mode)}</span></td><td>${p.enabled?'enabled':'disabled'}</td><td><div class="row-actions"><button data-edit-profile="${esc(p.id)}" class="secondary">编辑</button><button data-delete-profile="${esc(p.id)}" class="delete">删除</button></div></td></tr>`).join('')||'<tr><td colspan="7" class="muted">尚未配置审计模型</td></tr>';}
$('#profilesBody').addEventListener('click',async e=>{const edit=e.target.dataset.editProfile;if(edit){openProfile(state.profiles.find(x=>x.id===edit));return;}const del=e.target.dataset.deleteProfile;if(del&&confirm('删除后引用它的路由将退回仅规则审计，是否继续？')){try{await api('audit-profiles/'+del,{method:'DELETE'});toast('审计模型已删除');loadProfiles();}catch(err){toast(err.message,true);}}});
$('#newProfileBtn').addEventListener('click',()=>openProfile(null));function openProfile(p){const f=$('#profileForm');f.reset();f.elements.id.value=p?.id||'';f.elements.name.value=p?.name||'';f.elements.endpoint.value=p?.endpoint||'';f.elements.model.value=p?.model||'';f.elements.fail_mode.value=p?.fail_mode||'closed';f.elements.block_threshold.value=p?.block_threshold??.72;f.elements.timeout_ms.value=p?.timeout_ms||8000;f.elements.max_input_chars.value=p?.max_input_chars||32000;f.elements.cache_ttl_seconds.value=p?.cache_ttl_seconds??600;f.elements.system_prompt.value=p?.system_prompt||'';f.elements.enabled.checked=p?p.enabled:true;$('#profileDialog').showModal();}
$('#profileForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;const body={name:f.elements.name.value,endpoint:f.elements.endpoint.value,model:f.elements.model.value,api_key:f.elements.api_key.value,fail_mode:f.elements.fail_mode.value,block_threshold:Number(f.elements.block_threshold.value),timeout_ms:Number(f.elements.timeout_ms.value),max_input_chars:Number(f.elements.max_input_chars.value),cache_ttl_seconds:Number(f.elements.cache_ttl_seconds.value),system_prompt:f.elements.system_prompt.value,enabled:f.elements.enabled.checked};const id=f.elements.id.value;try{await api(id?'audit-profiles/'+id:'audit-profiles',{method:id?'PUT':'POST',body:JSON.stringify(body)});$('#profileDialog').close();toast('审计模型已保存');loadProfiles();}catch(err){toast(err.message,true);}});

async function loadRules(){const d=await api('rules');state.rules=d.items||[];$('#rulesBody').innerHTML=state.rules.map(r=>`<tr><td><b>${esc(r.name)}</b></td><td>${esc(r.category)}</td><td><span class="badge ${r.action==='block'?'bad':r.action==='review'?'warn':'good'}">${esc(r.action)}</span> ${esc(r.score)}</td><td>${esc(r.priority)}</td><td>${r.builtin?'内置':'自定义'}</td><td>${r.enabled?'enabled':'disabled'}</td><td><div class="row-actions"><button data-edit-rule="${esc(r.id)}" class="secondary">编辑</button>${r.builtin?'':`<button data-delete-rule="${esc(r.id)}" class="delete">删除</button>`}</div></td></tr>`).join('')||'<tr><td colspan="7" class="muted">尚无规则</td></tr>';}
$('#rulesBody').addEventListener('click',async e=>{const edit=e.target.dataset.editRule;if(edit){openRule(state.rules.find(x=>x.id===edit));return;}const del=e.target.dataset.deleteRule;if(del&&confirm('确定删除此规则？')){try{await api('rules/'+del,{method:'DELETE'});toast('规则已删除');loadRules();}catch(err){toast(err.message,true);}}});
$('#newRuleBtn').addEventListener('click',()=>openRule(null));function openRule(r){const f=$('#ruleForm');f.reset();f.elements.id.value=r?.id||'';f.elements.name.value=r?.name||'';f.elements.category.value=r?.category||'';f.elements.pattern.value=r?.pattern||'';f.elements.action.value=r?.action||'block';f.elements.score.value=r?.score??1;f.elements.priority.value=r?.priority||100;f.elements.enabled.checked=r?r.enabled:true;$('#ruleDialog').showModal();}
$('#ruleForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;const body={name:f.elements.name.value,category:f.elements.category.value,pattern:f.elements.pattern.value,action:f.elements.action.value,score:Number(f.elements.score.value),priority:Number(f.elements.priority.value),enabled:f.elements.enabled.checked};const id=f.elements.id.value;try{await api(id?'rules/'+id:'rules',{method:id?'PUT':'POST',body:JSON.stringify(body)});$('#ruleDialog').close();toast('规则已保存');loadRules();}catch(err){toast(err.message,true);}});

async function loadTraces(){const f=new FormData($('#traceFilter'));const q=new URLSearchParams();for(const[k,v]of f.entries())if(v)q.set(k,v);q.set('limit','200');const d=await api('traces?'+q.toString());$('#tracesBody').innerHTML=(d.items||[]).map(t=>`<tr><td>${esc(new Date(t.created_at).toLocaleString())}<div class="mono muted">${esc(t.external_request_id||t.id)}</div></td><td><b>${esc(t.route_slug||'-')}</b><div class="muted">${esc(t.model||'-')}</div></td><td><span class="badge ${t.normalized_code===555?'bad':t.outcome==='allowed'?'good':'warn'}">${esc(t.outcome||'-')}</span></td><td>${esc(t.http_status)}${t.normalized_code?` / ${esc(t.normalized_code)}`:''}</td><td>${esc(t.risk_category||'-')}<div class="muted">${esc(t.risk_score||0)} · ${esc(t.risk_reason_code||'')}</div></td><td>${esc(t.total_latency_ms)} ms<div class="muted">audit ${esc(t.audit_latency_ms)} / upstream ${esc(t.upstream_latency_ms)}</div></td></tr>`).join('')||'<tr><td colspan="6" class="muted">没有匹配的请求</td></tr>';}
$('#traceFilter').addEventListener('submit',e=>{e.preventDefault();loadTraces().catch(err=>toast(err.message,true));});

async function loadStorage(){const p=await api('storage-policy');const f=$('#storageForm');for(const name of['retention_days','redis_buffer_ttl_hours','kafka_retention_hours'])f.elements[name].value=p[name];for(const name of['postgres_enabled','redis_buffer_enabled','kafka_enabled'])f.elements[name].checked=!!p[name];}
$('#storageForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;const body={retention_days:Number(f.elements.retention_days.value),postgres_enabled:f.elements.postgres_enabled.checked,redis_buffer_enabled:f.elements.redis_buffer_enabled.checked,redis_buffer_ttl_hours:Number(f.elements.redis_buffer_ttl_hours.value),kafka_enabled:f.elements.kafka_enabled.checked,kafka_retention_hours:Number(f.elements.kafka_retention_hours.value),store_raw_prompt:false};try{await api('storage-policy',{method:'PUT',body:JSON.stringify(body)});toast('存储策略已保存');}catch(err){toast(err.message,true);}});

$('#dryRunForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;$('#dryRunResult').textContent='执行中…';try{const d=await api('audit/dry-run',{method:'POST',body:JSON.stringify({profile_id:f.elements.profile_id.value||null,text:f.elements.text.value})});$('#dryRunResult').textContent=JSON.stringify(d,null,2);}catch(err){$('#dryRunResult').textContent=err.message;toast(err.message,true);}});

if(state.token)showApp();else logout();
